import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
	<html lang="en">
		<body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
			<header className="p-4 font-bold">
				<nav className="container mx-auto flex items-center">
					<div className="flex-grow">
						<Link href="/"
							className="font-bold"
						>
							Home
						</Link>
					</div>
					<div className="flex space-x-4">
						<Link href="/portfolio"
								className="font-bold"
						>
							Portfolio
						</Link>
						<Link href="/contact"
								className="font-bold"
						>
							Contact
						</Link>
					</div>
				</nav>
			</header>
			<main className="flex-grow">{children}</main> 
	  </body>
	</html>
  );
}
